apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: plugin-
  labels:
    workflows.argoproj.io/test: "true"
spec:
  entrypoint: main
  templates:
    - name: main
      plugin:
        hello: { }