kind: Secret
apiVersion: v1
metadata:
  name: argo-server-oauth2
stringData:
  issuer: http://dex:5556/dex
  clientId: argo-server
  clientSecret: ZXhhbXBsZS1hcHAtc2VjcmV0
  redirectUrl: https://localhost:2746/oauth2/callback