apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../namespace-install
  - minio
  - dex

resources:
  - argo-server-oauth2-secret.yaml
  - workflow-role.yaml
  - workflow-default-rolebinding.yaml
  - cluster-workflow-template-rbac.yaml

patchesStrategicMerge:
  - overlays/workflow-controller-configmap.yaml
  - overlays/argo-server-deployment.yaml