apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workflowagents.argoproj.io
spec:
  group: argoproj.io
  names:
    kind: WorkflowAgent
    listKind: WorkflowAgentList
    plural: workflowagents
    singular: workflowagent
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        required:
        - metadata
        - spec
        - status
        type: object
    served: true
    storage: true
