apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workflowtasks.argoproj.io
spec:
  group: argoproj.io
  names:
    kind: WorkflowTask
    listKind: WorkflowTaskList
    plural: workflowtasks
    singular: workflowtask
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Template
      jsonPath: .spec.name
      name: Template
      type: string
    - description: Status
      jsonPath: .status.phase
      name: Status
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        required:
        - metadata
        type: object
    served: true
    storage: true
    subresources:
      status: {}
