apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-server-read-only
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-server-read-only
subjects:
- kind: ServiceAccount
  name: argo-server-read-only
