apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-server-config-volume
data:
  model.conf: |
    [request_definition]
    r = sub, obj, act

    [policy_definition]
    p = sub, obj, act

    [role_definition]
    g = _, _

    [policy_effect]
    e = some(where (p.eft == allow))

    [matchers]
    m = g(r.sub, p.sub) && keyMatch(r.obj, p.obj) && keyMatch(r.act, p.act)
  policy.csv: |
    p, admin, *, *
    p, authors, *, *
